const postersTypes = {
  FETCH_POSTERS_START: 'FETCH_POSTERS_START',
  FETCH_POSTERS_SUCCESS: 'FETCH_POSTERS_SUCCESS',
  FETCH_POSTERS_FAILURE: 'FETCH_POSTERS_FAILURE'
};

export default postersTypes;
