const movieTypes = {
  FETCH_MOVIE_START: 'FETCH_MOVIE_START',
  FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
  FETCH_MOVIE_FAILURE: 'FETCH_MOVIE_START',
  GET_MOVIE_ID: 'GET_MOVIE_ID'
};

export default movieTypes;
