const movieTypes = {
  FETCH_MOVIE_START: 'FETCH_MOVIE_START',
  FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
  FETCH_MOVIE_FAILURE: 'FETCH_MOVIE_FAILURE',
  GET_MOVIE_ID: 'GET_MOVIE_ID',
  SET_MOVIE_BACKGROUND: 'SET_MOVIE_BACKGROUND',
  DELETE_MOVIE_BACKGROUND: 'DELETE_MOVIE_BACKGROUND'
};

export default movieTypes;
