const moviesTypes = {
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_START',
  FETCH_MOVIES_GENRES_START: 'FETCH_MOVIES_GENRES_START',
  FETCH_MOVIES_GENRES_SUCCESS: 'FETCH_MOVIES_GENRES_SUCCESS',
  FETCH_MOVIES_GENRES_FAILURE: 'FETCH_MOVIES_GENRES_START'
};

export default moviesTypes;
