const moviesTypes = {
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_START',
  FETCH_MOVIES_GENRES_START: 'FETCH_MOVIES_GENRES_START',
  FETCH_MOVIES_GENRES_SUCCESS: 'FETCH_MOVIES_GENRES_SUCCESS',
  FETCH_MOVIES_GENRES_FAILURE: 'FETCH_MOVIES_GENRES_START',
  FETCH_MOVIES_SEARCH_START: 'FETCH_MOVIES_SEARCH_START',
  FETCH_MOVIES_SEARCH_SUCCESS: 'FETCH_MOVIES_SEARCH_SUCCESS',
  FETCH_MOVIES_SEARCH_FAILURE: 'FETCH_MOVIES_SEARCH_START',
  GET_QUERY_VALUE: 'GET_QUERY_VALUE',
  NEXT_PAGE: 'NEXT_PAGE',
  PREV_PAGE: 'PREV_PAGE'
};

export default moviesTypes;
