const navigationTypes = {
  FETCH_GENRES_START: 'FETCH_GENRES_START',
  FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
  FETCH_GENRES_FAILURE: 'FETCH_GENRES_FAILURE',
  GET_SELECTED_MENU: 'GET_GENRE_NAME',
  GET_MENU_ID: 'GET_MENU_ID'
};

export default navigationTypes;
